### ISSUE TITLE
Rev 2 editor pre-launch checklist 

### ISSUE THREAD

**Issue by TomWhitwell** [TomWhitwell/8mu_Public#7]
- [x] Add screengrab to homepage 
- [x] More noticeable styling for new firmware 
- [ ] Copy to smith takehashi repo 
- [ ] Add [.github/workflows](https://github.com/TomWhitwell/test-host/tree/main/.github/workflows)
